AwarenessGrows.Web/Controllers/TakeActionController.cs
using AwarenessGrows.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AwarenessGrows.Web.Controllers
{
    public class TakeActionController : BaseController
    {
        // GET: TakeAction
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WriteSenator()
        {
            ContactInfoViewModel model = new ContactInfoViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult WriteSenator(ContactInfoViewModel model)
        {
            if (model.State.Length != 2 || String.IsNullOrWhiteSpace(model.State))
                return RedirectToAction("Index");

            return Redirect("http://www.senate.gov/general/contact_information/senators_cfm.cfm?State=" + model.State.ToUpper());
            
        }

        public ActionResult WriteHouseRep()
        {
            ContactInfoViewModel model = new ContactInfoViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult WriteHouseRep(ContactInfoViewModel model)
        {
            if (model.ZipCode.Length != 5 || String.IsNullOrWhiteSpace(model.ZipCode))
                return RedirectToAction("Index");


            return Redirect("http://ziplook.house.gov/htbin/findrep?ZIP=" + model.ZipCode+"&Submit=FIND+YOUR+REP+BY+ZIP");
        }
    }
}

AwarenessGrows.Web/Views/Shared/_Alerts.cshtml
@using System.Configuration
@using AwarenessGrows.Web.Helpers

@{
    var appliationRegion = ConfigurationManager.AppSettings["ApplicationRegion"];
    switch (appliationRegion)
    {
        case WebConstants.ApplicationRegions.DEVELOPMENT:
            <div class="alert alert-danger">
                @WebConstants.ApplicationRegions.DEVELOPMENTMESSAGE
            </div>
            break;
        case WebConstants.ApplicationRegions.TEST:
        <div class="alert alert-danger">
            @WebConstants.ApplicationRegions.TESTMESSAGE
        </div>
            break;
        case WebConstants.ApplicationRegions.PRODUCTION:
        <div class="alert alert-info" style="display: none;">
            @WebConstants.ApplicationRegions.PRODUCTIONMESSAGE
        </div>
            break;
        default:
        <div class="alert alert-danger">
            @WebConstants.ApplicationRegions.UNKNOWNMESSAGE
        </div>
            break;
    }
}

@foreach (string key in WebConstants.Alerts.ALL)
{
    if (TempData.ContainsKey(key))
    {
        <div class="alert alert-@key">
            <button type="button" class="close" data-dismiss="alert">x</button>
            @Html.Raw(TempData[key].ToString())
            @*@TempData[key]*@
        </div>
    }
}

AwarenessGrows.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Awareness Grows</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"0a42d22c-fdb4-4b78-993c-614d6cec40df"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" Awareness Grows", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Library", "Index","Library")</li>
                    <li>@Html.ActionLink("Take Action", "Index", "TakeAction")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Awareness Grows YOU!</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AwarenessGrows.Web/Views/Shared/_LayoutMetro.cshtml
@using System.Configuration

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0">*@
    <title>@ConfigurationManager.AppSettings["ApplicationNameSpace"] | @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    @Styles.Render("~/Content/themes/base/css")
    @*@Styles.Render("~/Content/css")*@
    @Styles.Render("~/Content/Metro/css")


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="~/Scripts/html5shiv.js"></script>
        <script src="~/Scripts/respond.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/es5-shim/2.2.0/es5-shim.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @*@Scripts.Render("~/bundles/jqueryval")*@

    <script src="~/Scripts/Metro/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.2.min.js"></script>
    <script src="~/Scripts/Metro/bootstrap.js"></script>
    <script src="~/Scripts/Metro/ui-load.js"></script>
    <script src="~/Scripts/Metro/ui-jp.config.js"></script>
    <script src="~/Scripts/Metro/ui-jp.js"></script>
    <script src="~/Scripts/Metro/ui-nav.js"></script>
    <script src="~/Scripts/Metro/ui-toggle.js"></script>



    @RenderSection("HeadScripts", required: false)


</head>
<body>
    <div class="app app-header-fixed backGroundImage">

        <!-- header -->
        <header id="header" class="app-header navbar bg-primary" role="menu">
            <!-- navbar header -->
            <div class="navbar-header box-shadow-inset">

                <div class="navbar-collapse hidden-xs">


                    @Html.Partial("_LoginPartial")
                </div>

            </div>


        </header>

        <aside id="aside" class="app-aside hidden-xs bg-primary lt">
            <div class="app-aside-inner" bs-affix>
                <div class="app-aside-body scrollable hover">
                    <nav ui-nav>
                        <ul class="nav">
                            <li class="nav-header h4 m-v-sm">
                                Navigation
                            </li>


                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Library", "Index", "Library")</li>
                            <li>@Html.ActionLink("Take Action", "Index", "TakeAction")</li>

                        </ul>
                    </nav>
                </div>
                <div class="app-aside-footer p text-xs text-center">
                </div>
            </div>
        </aside>

        <div id="content" class="app-content" role="main">
            <div class="p-h-md p-v box-shadow pos-rlt bannerImageXX">
                @Html.Partial("_Alerts")
                @RenderBody()

            </div>
        </div>



        <!-- / content -->
        <!-- footer -->
        <footer id="footer" class="app-footer" role="footer"></footer>
        <!-- / footer -->
    </div>
    @RenderSection("scripts", required: false)

</body>
</html>